### ISSUE TITLE
provided assembler is out of sync with generator code

### ISSUE THREAD

**Issue by afk11** [tmthrgd/go-hex#5]
asm_gen.go looks like it has taken care of the support_avx issue, but pulling in latest commit of this library still uses the old runtime.support_avx

Tempted to PR a check for travis that the generator produces the same output as the committed files, that way people don't have to generate it themselves?

**Comment by tmthrgd** [comment]
I don't follow. No where in `asm_gen.go`, `hex_encode_amd64.s` or `hex_decode_amd64.s` does the string "runtime" or "support_avx" occur. That was removed in a82aa03cedda71045967f5cc69c22cada26f4e6c back in May. Feature detection has been using `x/sys/cpu` since then.

As for running the generator, that is not advisable. The generator is only meant to be run by me or anyone modifying the library. Consumers are never meant to run the generator.

**Comment by afk11** [comment]
Thanks, my mistake!
